In [1]:
import numpy as np
import pandas as pd
import ipyvolume as ipv
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import cv2
import ast
from skimage.feature import hog

In [2]:
dataset = pd.read_csv("Enhanced_dataset.csv")
data = dataset[['filename','region_shape_attributes','region_attributes']]

In [3]:
print(data['filename'])

0      scene00001.png
1      scene00001.png
2      scene00001.png
3      scene00001.png
4      scene00031.png
            ...      
838    scene03421.png
839    scene03721.png
840    scene03781.png
841    scene04231.png
842    scene04801.png
Name: filename, Length: 843, dtype: object


In [4]:
type(data['region_shape_attributes'])

pandas.core.series.Series

In [5]:
#z = data.region_shape_attributes
#print(z[0])
#res = ast.literal_eval(z[0])
#print(res['x'])
x_coor = []
y_coor = []
height = []
width = []
count = 0

for z in data.region_shape_attributes:
    res = ast.literal_eval(z)
    x_coor.append(res['x'])
    y_coor.append(res['y'])
    height.append(res['height'])
    width.append(res['width'])

#print(x_coor)
Motorcycle = []
Helmet = []
for z in data.region_attributes:
    res = ast.literal_eval(z)
    Motorcycle.append(res['Motorcycle'])
    Helmet.append(res['Driver Helmet'])
    
#print(x_coor)
#print(y_coor)
#print(height)
#print(width)
#print(Motorcycle)
#print(Helmet)

In [6]:
FinalDF = pd.DataFrame({'image name' : data['filename'],'x_coordinate' : x_coor,'y_coordinate' : y_coor,'height' : height,'width' : width,
                       'Motorcycle' : Motorcycle,'Helmet' : Helmet})

In [7]:
print(FinalDF)

         image name  x_coordinate  y_coordinate  height  width Motorcycle  \
0    scene00001.png           882           276     182    198         No   
1    scene00001.png           356           248     113     72        Yes   
2    scene00001.png           452           155     109     76        Yes   
3    scene00001.png           145           614      99    145        Yes   
4    scene00031.png           461           387     146     72        Yes   
..              ...           ...           ...     ...    ...        ...   
838  scene03421.png           480            80      90     69        Yes   
839  scene03721.png           574           128     135    123         No   
840  scene03781.png           492            96     103     76        Yes   
841  scene04231.png           935           345     295    280         No   
842  scene04801.png           836           507     207    220        Yes   

    Helmet  
0       No  
1       No  
2      Yes  
3       No  
4      Yes

In [8]:
path = 'Experi_imag/scene03421.png'
img = cv2.imread(path)
crop = img[45:(45+25),895:(895+54)]
resized = cv2.resize(crop,(64,128),interpolation = cv2.INTER_AREA)
cv2.imshow('image',img)
cv2.imshow('crop',crop)
cv2.imshow('resized',resized)
k = cv2.waitKey()
if k == 27:
    cv2.destroyAllWindows()

In [9]:
#cv2.imshow('image',img)
#crop1 = img[y_coor[2]:(y_coor[2]+height[2]),x_coor[2]:(x_coor[2]+width[2])]
#cv2.imshow('cropped_img',crop)

In [10]:
hog_features = []
hog_images = []
for i in range(int(len(data['filename']))):
    path = 'Experi_imag/'+data['filename'][i]
    img = cv2.imread(path)
    #print(ssize)
    frame1 = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    filter_img = cv2.GaussianBlur(frame1,(5,5),100)
    crop = filter_img[y_coor[i]:(y_coor[i]+height[i]),x_coor[i]:(x_coor[i]+width[i])]
    print(i)
    print(y_coor[i])
    print(height[i])
    print(x_coor[i])
    print(width[i])
    print(crop.shape)
    print()
    resized = cv2.resize(crop,(64,128),interpolation = cv2.INTER_AREA)
    hf,hi = hog(resized, orientations=9, pixels_per_cell=(8,8),cells_per_block=(2, 2),visualize = True)
    hog_images.append(hi)
    hog_features.append(hf)
    cv2.destroyAllWindows()


#print(hog_features)

0
276
182
882
198
(182, 198)

1
248
113
356
72
(113, 72)

2
155
109
452
76
(109, 76)

3
614
99
145
145
(99, 145)

4
387
146
461
72
(146, 72)

5
587
119
91
135
(119, 135)

6
320
151
344
99
(151, 99)

7
135
90
434
62
(90, 62)

8
72
91
498
53
(91, 53)

9
295
140
316
104
(140, 104)

10
153
118
542
68
(118, 68)

11
158
105
449
69
(105, 69)

12
51
77
481
50
(77, 50)

13
4
73
748
45
(73, 45)

14
14
67
532
42
(67, 42)

15
214
114
932
67
(114, 67)

16
162
125
799
78
(125, 78)

17
41
116
817
78
(116, 78)

18
392
143
299
105
(143, 105)

19
496
166
181
112
(166, 112)

20
434
246
395
189
(246, 189)

21
144
107
413
72
(107, 72)

22
69
82
489
73
(82, 73)

23
412
168
1005
130
(168, 130)

24
169
123
876
81
(123, 81)

25
444
169
333
110
(169, 110)

26
570
139
281
105
(139, 105)

27
264
113
350
71
(113, 71)

28
196
108
417
77
(108, 77)

29
167
146
526
108
(146, 108)

30
77
78
465
62
(78, 62)

31
26
76
814
42
(76, 42)

32
440
189
985
107
(189, 107)

33
140
107
903
62
(107, 62)

34
130
107
779
71
(107, 71)

281
347
180
1069
113
(180, 113)

282
342
202
930
116
(202, 116)

283
154
134
856
105
(134, 105)

284
349
146
261
105
(146, 105)

285
205
146
390
85
(146, 85)

286
95
108
471
64
(108, 64)

287
77
103
575
89
(103, 89)

288
326
195
947
128
(195, 128)

289
99
103
860
72
(103, 72)

290
169
107
377
69
(107, 69)

291
283
116
443
95
(116, 95)

292
95
78
460
73
(78, 73)

293
14
81
596
67
(81, 67)

294
225
163
943
94
(163, 94)

295
485
182
375
135
(182, 135)

296
121
110
503
72
(110, 72)

297
98
96
449
39
(96, 39)

298
538
169
149
126
(169, 126)

299
570
149
1126
140
(149, 140)

300
245
121
402
83
(121, 83)

301
190
104
520
72
(104, 72)

302
37
89
539
48
(89, 48)

303
37
77
476
48
(77, 48)

304
64
92
556
85
(92, 85)

305
82
98
487
60
(98, 60)

306
222
117
372
100
(117, 100)

307
78
98
474
55
(98, 55)

308
9
69
529
51
(69, 51)

309
267
122
349
103
(122, 103)

310
15
68
521
44
(68, 44)

311
113
108
454
81
(108, 81)

312
28
83
824
56
(83, 56)

313
33
83
499
63
(83, 63)

314
116
110
881
78
(110, 78)

557
17
91
526
71
(91, 71)

558
263
149
342
114
(149, 114)

559
32
118
575
86
(118, 86)

560
140
119
434
105
(119, 105)

561
50
117
487
119
(117, 119)

562
12
89
534
94
(89, 94)

563
469
212
402
181
(212, 181)

564
139
149
410
135
(149, 135)

565
130
112
571
87
(112, 87)

566
168
126
514
59
(126, 59)

567
74
109
433
116
(109, 116)

568
27
127
458
110
(127, 110)

569
472
223
271
245
(223, 245)

570
5
136
560
48
(136, 48)

571
68
154
814
134
(154, 134)

572
186
148
466
158
(148, 158)

573
1
92
487
112
(92, 112)

574
49
107
538
109
(107, 109)

575
200
143
770
109
(143, 109)

576
63
109
867
78
(109, 78)

577
77
127
747
104
(127, 104)

578
399
189
245
184
(189, 184)

579
523
193
827
132
(193, 132)

580
229
162
967
89
(162, 89)

581
141
122
895
77
(122, 77)

582
220
190
800
136
(190, 136)

583
36
101
854
58
(101, 58)

584
23
105
727
89
(105, 89)

585
172
119
919
85
(119, 85)

586
438
204
1057
117
(204, 117)

587
160
101
426
103
(101, 103)

588
135
158
742
136
(158, 136)

589
453
213
1099
119


831
131
103
426
70
(103, 70)

832
107
82
540
104
(82, 104)

833
1
82
568
90
(82, 90)

834
250
125
333
90
(125, 90)

835
273
155
480
110
(155, 110)

836
238
186
1013
103
(186, 103)

837
84
96
542
93
(96, 93)

838
80
90
480
69
(90, 69)

839
128
135
574
123
(135, 123)

840
96
103
492
76
(103, 76)

841
345
295
935
280
(295, 280)

842
507
207
836
220
(207, 220)



In [11]:
print(hog_features[0])

[0.08219414 0.00875199 0.         ... 0.00683107 0.         0.        ]


In [12]:
pca = PCA(n_components = 3)
principalComponent = pca.fit_transform(hog_features)
principalDf = pd.DataFrame(data = principalComponent
             , columns = ['principal component 1', 'principal component 2', 'principal component 3'])
Motor = np.array(Motorcycle)
motor = Motor[:][:]
principalDf['Motorcycle'] = motor
Helmt = np.array(Helmet)
helmt = Helmt[:][:]
principalDf['Helmet'] = helmt

In [13]:
print(principalDf)

     principal component 1  principal component 2  principal component 3  \
0                 2.046190               2.470285               0.747667   
1                -0.234141              -1.932557              -0.331894   
2                -1.569175              -1.821717              -2.354131   
3                -1.409917              -0.723692               0.933251   
4                -0.547986              -0.245627               0.732278   
..                     ...                    ...                    ...   
838              -2.090126              -1.723648               1.213852   
839               4.795226               0.007063               0.182175   
840              -0.484470              -0.291705               2.108513   
841               1.154449               2.771326               1.375718   
842              -1.991859              -0.265395               0.715253   

    Motorcycle Helmet  
0           No     No  
1          Yes     No  
2          Yes 

In [14]:
m = principalDf[principalDf['Motorcycle'] == 'No']
print(m)

h = principalDf[principalDf['Helmet'] == 'No'] 
print(h)

     principal component 1  principal component 2  principal component 3  \
0                 2.046190               2.470285               0.747667   
18               -1.326876              -1.508048               0.952587   
20                4.101694              -1.340301               0.594673   
29                4.324525              -0.390810               0.291318   
41                3.578017               0.238930              -1.116833   
..                     ...                    ...                    ...   
832               2.756355              -0.699454               0.413258   
833               4.526026              -0.266507              -0.401283   
837               4.917592               0.463527               0.104242   
839               4.795226               0.007063               0.182175   
841               1.154449               2.771326               1.375718   

    Motorcycle Helmet  
0           No     No  
18          No     No  
20          No 

In [15]:
fig = ipv.figure()
ipv.scatter(principalDf['principal component 1'],principalDf['principal component 2'],principalDf['principal component 3'])
ipv.scatter(m['principal component 1'],m['principal component 2'],m['principal component 3'],color = 'blue',size = 4)
ipv.show()

In [16]:
ipv.save('motor(red)_vs_non-motor(blue).html')

In [17]:
fig = ipv.figure()
ipv.scatter(principalDf['principal component 1'],principalDf['principal component 2'],principalDf['principal component 3'])
ipv.scatter(m['principal component 1'],m['principal component 2'],m['principal component 3'],color = 'green',size = 6)
ipv.scatter(h['principal component 1'],h['principal component 2'],h['principal component 3'],color = 'blue',size = 4)
ipv.show()

In [18]:
ipv.save('motorwithhelmet(red),motorwithouthelmet(blue),non_motor(green).html')

In [19]:
features = np.array(hog_features)
print(features)

[[0.08219414 0.00875199 0.         ... 0.00683107 0.         0.        ]
 [0.09503838 0.0303589  0.09600325 ... 0.0135164  0.         0.03022358]
 [0.31480321 0.07772564 0.04915801 ... 0.28882251 0.20023153 0.07739784]
 ...
 [0.41363854 0.41363854 0.02518326 ... 0.04939292 0.09917805 0.26922554]
 [0.24515326 0.1069975  0.07361399 ... 0.03358033 0.112993   0.17652346]
 [0.23909472 0.08488045 0.03623164 ... 0.15839003 0.1920239  0.21079377]]


In [20]:
y_type = []
for i in Motorcycle:
    if i == 'Yes':
        y_type.append(1)
    else:
        y_type.append(0)

In [21]:
y_type = np.array(y_type)
print(y_type)

[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 1 1 0 1 0 0
 1 1 1 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0
 1 1 0 1 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 1 1 0 0 1 1 0 0 0 1 1 1
 1 0 0 0 1 0 1 0 1 0 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 1 0 0 1
 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 0 1 0 1 1 1 0
 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 1 1 1
 0 1 1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1
 1 0 1 1 1 1 1 0 0 1 0 0 1 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 0 0
 1 1 1 0 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

Using SVM Model..........................

In [22]:
file = pd.DataFrame(features)
print(file)

         0         1         2         3         4         5         6     \
0    0.082194  0.008752  0.000000  0.000000  0.031312  0.008752  0.022141   
1    0.095038  0.030359  0.096003  0.040479  0.090513  0.020239  0.012800   
2    0.314803  0.077726  0.049158  0.000000  0.052140  0.000000  0.314803   
3    0.442223  0.440293  0.085682  0.025684  0.074660  0.012842  0.016244   
4    0.189218  0.024889  0.157409  0.074666  0.200349  0.000000  0.078704   
..        ...       ...       ...       ...       ...       ...       ...   
838  0.208997  0.073789  0.093337  0.000000  0.175997  0.000000  0.124449   
839  0.348401  0.217018  0.153876  0.066354  0.217614  0.044236  0.083932   
840  0.413639  0.413639  0.025183  0.011262  0.121089  0.000000  0.000000   
841  0.245153  0.106998  0.073614  0.050540  0.245153  0.156723  0.245153   
842  0.239095  0.084880  0.036232  0.039118  0.179702  0.073491  0.054605   

         7         8         9     ...      3770      3771      3772  \
0  

In [23]:
file['Motorcycle'] = y_type
print(file.head())

          0         1         2         3         4         5         6  \
0  0.082194  0.008752  0.000000  0.000000  0.031312  0.008752  0.022141   
1  0.095038  0.030359  0.096003  0.040479  0.090513  0.020239  0.012800   
2  0.314803  0.077726  0.049158  0.000000  0.052140  0.000000  0.314803   
3  0.442223  0.440293  0.085682  0.025684  0.074660  0.012842  0.016244   
4  0.189218  0.024889  0.157409  0.074666  0.200349  0.000000  0.078704   

          7         8         9  ...      3771      3772      3773      3774  \
0  0.020184  0.000000  0.196023  ...  0.121549  0.158095  0.145572  0.062193   
1  0.000000  0.000000  0.470450  ...  0.334514  0.085485  0.202746  0.128228   
2  0.155451  0.000000  0.314803  ...  0.281877  0.113903  0.288823  0.200572   
3  0.025684  0.023679  0.442223  ...  0.308556  0.000000  0.004376  0.000000   
4  0.049777  0.000000  0.178088  ...  0.088846  0.060440  0.324568  0.300502   

       3775      3776      3777      3778      3779  Motorcycle  
0 

In [24]:
#file.to_csv('Dataset_SVM.csv')

In [25]:
FinalDF.head()

image name  x_coordinate  y_coordinate  height  width Motorcycle Helmet
0  scene00001.png           882           276     182    198         No     No
1  scene00001.png           356           248     113     72        Yes     No
2  scene00001.png           452           155     109     76        Yes    Yes
3  scene00001.png           145           614      99    145        Yes     No
4  scene00031.png           461           387     146     72        Yes    Yes

In [26]:
Two_wheelers = FinalDF[FinalDF['Motorcycle'] == 'Yes']

In [27]:
index = []
for i in range(0,int(len(Two_wheelers['image name']))):
    index.append(i)
#print(index)
Two_wheelers['index'] = index

C:\Users\VENKATESH BHUTRA\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [28]:
Two_wheelers.head()

image name  x_coordinate  y_coordinate  height  width Motorcycle  \
1  scene00001.png           356           248     113     72        Yes   
2  scene00001.png           452           155     109     76        Yes   
3  scene00001.png           145           614      99    145        Yes   
4  scene00031.png           461           387     146     72        Yes   
5  scene00031.png            91           587     119    135        Yes   

  Helmet  index  
1     No      0  
2    Yes      1  
3     No      2  
4    Yes      3  
5     No      4

In [29]:
hist_vector = []
for i in Two_wheelers['image name']:
    path = 'Experi_imag/'+ i 
    img = cv2.imread(path,0)
    resized = cv2.resize(img,(64,128),interpolation = cv2.INTER_AREA)
    height = resized.shape[0]
    width = resized.shape[1]
    crop = resized[0:int(height*0.25),0:width]
    hsv = cv2.applyColorMap(crop,cv2.COLORMAP_HSV)
    hist = cv2.calcHist([crop],[0],None,[256],[0,256])
    hist_vector.append(hist)

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
scaler.fit(hist_vector[0]) 

StandardScaler(copy=True, with_mean=True, with_std=True)

In [31]:
pca1 = PCA(n_components = 3)
pC1 = pca1.fit_transform(hist_vector[0])
pDf = pd.DataFrame(data = pC1
             , columns = ['helmet principal component 1', 'helmet principal component 2', 'helmet principal component 3'])

ValueError: n_components=3 must be between 0 and min(n_samples, n_features)=1 with svd_solver='full'